### ISSUE TITLE
Lesson 18 HomeWork Task 2

### ISSUE THREAD

**Issue by DinamickaDevelopment** [e-serdyuk/DD_CompetencyCenter-Serdyuk#17]
![image](https://user-images.githubusercontent.com/12965606/27339029-529b62be-55df-11e7-9779-05f47d8f89f0.png)
Результат

**Comment by e-serdyuk** [comment]
У меня показывалось так https://gyazo.com/156a1b424397eff067aecc770f5c8a9b
Добавил кодировку,на всякий случай.
