### ISSUE TITLE
Angular, Home Work 1, Task2

### ISSUE THREAD

**Issue by DinamickaDevelopment** [e-serdyuk/DD_CompetencyCenter-Serdyuk#2]
Синтаксические ошибки при копировании. 
Зачем нужен:  $scope.Index = -1? Напишите в комментариях.

**Comment by e-serdyuk** [comment]
Исправил все синтаксические ошибки! 
По поводу индекса, я понял ход Ваших мыслей, я имел ввиду "обнуление индекса". Смысла в этом нет, так как при нажатии на кнопку save мы перезаписываем индекс. Исправил.
