### ISSUE TITLE
Lessons 15, Task 1, Class Work

### ISSUE THREAD

**Issue by DinamickaDevelopment** [e-serdyuk/DD_CompetencyCenter-Serdyuk#9]
Подумайте над тем как можно организовать обработку ошибок.

**Comment by e-serdyuk** [comment]
Проверка деления на 0
Мы после клика на кнопку сразу проверяем строку(есть ли в ней символ /)
Если есть, то проверяем следующий символ, если он 0(и если он оказывается последним символом, так как возможно деление на 08, например), то выдаем сообщение об ошибке, и функцию не выполняем
Обработка двойного нажатия там есть, обработка ввода текста тоже есть
Вводить большие числа разрешается и калькулятор их считает
